services:
  - type: web
    name: bookscope-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn bookscope.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "bookscope-api.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
