# Generated by Django 4.2.30 on 2026-04-13 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_volume_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('isbn10', models.CharField(blank=True, max_length=20)),
                ('isbn13', models.CharField(blank=True, max_length=20)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('published_date_raw', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('preview_link', models.URLField(blank=True, max_length=500)),
                ('info_link', models.URLField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('average_external_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('external_rating_count', models.PositiveIntegerField(default=0)),
                ('source_name', models.CharField(default='google_books', max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='catalog.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='catalog.genre')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
